/**
 * Les NOMS des icônes de la console, sans la bibliothèque : `web/lib/*` (navigation, blocs du builder, boutons
 * RCS) désigne une icône par son nom, et ces modules sont aussi compilés par le typecheck de la racine, qui n'a
 * pas `@phosphor-icons/react`. `components/Icone.tsx` associe chaque nom à son dessin et le typage exige les
 * deux listes identiques (un nom sans dessin, ou un dessin sans nom, ne compile pas).
 */
export const NOMS_ICONES = [
  'accueil',
  'inbox',
  'contacts',
  'campagnes',
  'chaine',
  'publicites',
  'contenu',
  'analytics',
  'scenario',
  'automation',
  'aide',
  'developpeurs',
  'securite',
  'outils',
  'ia',
  'baguette',
  'reglages',
  'menu',
  'deplier',
  'precedent',
  'suivant',
  'fermer',
  'ajouter',
  'supprimer',
  'modifier',
  'lien',
  'televerser',
  'ecouter',
  'voir',
  'idee',
  'smiley',
  'valide',
  'refuse',
  'attention',
  'echec',
  'hausse',
  'baisse',
  'stable',
  'modele',
  'formulaire',
  'mobile',
  'message',
  'email',
  'envoi',
  'piece',
  'image',
  'video',
  'micro',
  'clic',
  'entreprise',
  'telephone',
  'calendrier',
  'carte',
  'position',
  'carnet',
  'fichier',
  'webhook',
  'reponse',
  'question',
  'etiquette',
  'condition',
  'attente',
  'chrono',
  'humain',
  'robot',
  'fonction',
  'bloc',
  'connaissance',
  'rechercher',
  'contact',
  'fin',
] as const;

export type NomIcone = (typeof NOMS_ICONES)[number];
